# Generated by Django 3.0.8 on 2022-01-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0003_auto_20220130_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='results',
            name='output',
            field=models.ImageField(null=True, upload_to='media/results/'),
        ),
    ]
