# Generated by Django 3.0.8 on 2022-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_v1', '0004_auto_20220130_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrenceModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='models/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='results',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='results',
            name='output',
            field=models.ImageField(null=True, upload_to='results/'),
        ),
    ]
